name: 'pr-ommente'
description: 'Adds PR changes as comment'

# Define your inputs here.
inputs:
  owner:
    description: 'The owner of the repository'
    required: true
  repo:
    description: 'The repository name'
    required: true
  pr_number:
    description: 'The pull request number'
    required: true
  token:
    description: 'The GitHub token'
    required: true

runs:
  using: node20
  main: dist/index.js
